-- R__dev_auth_seed.sql
-- DEV ONLY.
-- Add classpath:db/devdata to Flyway locations only in the dev profile.
--
-- Test credentials:
-- user@local.dev       / DevUser123!
-- manager@local.dev    / DevManager123!
-- admin@local.dev      / DevAdmin123!
-- locked@local.dev     / DevLocked123!
-- disabled@local.dev   / DevDisabled123!
-- unverified@local.dev / DevVerify123!
--
-- Passwords are BCrypt hashes generated by PostgreSQL pgcrypto.
-- Never deploy fixed development passwords to production.

CREATE EXTENSION IF NOT EXISTS pgcrypto;


INSERT INTO auth_user (
    email,
    username,
    password_hash,
    enabled,
    email_verified,
    account_non_locked,
    failed_login_attempts,
    locked_until
)
VALUES
    (
        'user@local.dev',
        'dev-user',
        crypt('DevUser123!', gen_salt('bf', 12)),
        TRUE, TRUE, TRUE, 0, NULL
    ),
    (
        'manager@local.dev',
        'dev-manager',
        crypt('DevManager123!', gen_salt('bf', 12)),
        TRUE, TRUE, TRUE, 0, NULL
    ),
    (
        'admin@local.dev',
        'dev-admin',
        crypt('DevAdmin123!', gen_salt('bf', 12)),
        TRUE, TRUE, TRUE, 0, NULL
    ),
    (
        'locked@local.dev',
        'dev-locked',
        crypt('DevLocked123!', gen_salt('bf', 12)),
        TRUE, TRUE, FALSE, 5, CURRENT_TIMESTAMP + INTERVAL '24 hours'
    ),
    (
        'disabled@local.dev',
        'dev-disabled',
        crypt('DevDisabled123!', gen_salt('bf', 12)),
        FALSE, TRUE, TRUE, 0, NULL
    ),
    (
        'unverified@local.dev',
        'dev-unverified',
        crypt('DevVerify123!', gen_salt('bf', 12)),
        TRUE, FALSE, TRUE, 0, NULL
    )
ON CONFLICT DO NOTHING;


-- Main role assignments.
INSERT INTO security_user_role (user_id, role_id)
SELECT u.id, r.id
FROM auth_user u
JOIN security_role r
  ON (
      (u.email IN ('user@local.dev', 'locked@local.dev', 'disabled@local.dev', 'unverified@local.dev')
       AND r.code = 'ROLE_USER')
      OR
      (u.email = 'manager@local.dev' AND r.code = 'ROLE_MANAGER')
      OR
      (u.email = 'admin@local.dev' AND r.code = 'ROLE_ADMIN')
  )
ON CONFLICT DO NOTHING;


-- Useful audit fixtures.
INSERT INTO auth_audit_event (
    user_id,
    principal,
    event_type,
    success,
    ip_address,
    user_agent,
    details
)
SELECT
    u.id,
    u.email,
    'LOGIN_SUCCESS',
    TRUE,
    '127.0.0.1'::INET,
    'dev-seed',
    '{"source":"flyway-dev-seed"}'::JSONB
FROM auth_user u
WHERE u.email IN ('user@local.dev', 'manager@local.dev', 'admin@local.dev')
AND NOT EXISTS (
    SELECT 1
    FROM auth_audit_event e
    WHERE e.user_id = u.id
      AND e.event_type = 'LOGIN_SUCCESS'
      AND e.user_agent = 'dev-seed'
);


INSERT INTO auth_audit_event (
    user_id,
    principal,
    event_type,
    success,
    ip_address,
    user_agent,
    details
)
SELECT
    u.id,
    u.email,
    'LOGIN_LOCKED',
    FALSE,
    '127.0.0.1'::INET,
    'dev-seed',
    '{"reason":"too_many_failed_attempts","source":"flyway-dev-seed"}'::JSONB
FROM auth_user u
WHERE u.email = 'locked@local.dev'
AND NOT EXISTS (
    SELECT 1
    FROM auth_audit_event e
    WHERE e.user_id = u.id
      AND e.event_type = 'LOGIN_LOCKED'
      AND e.user_agent = 'dev-seed'
);
