-- V2__create_auth_schema.sql
-- Production-safe schema for authentication/authorization.
-- Raw passwords and raw security tokens must NEVER be stored here.

CREATE TABLE auth_user (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   VARCHAR(320) NOT NULL,
    username                VARCHAR(80) NOT NULL,
    password_hash           VARCHAR(100) NOT NULL,

    enabled                 BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified          BOOLEAN NOT NULL DEFAULT FALSE,
    account_non_locked      BOOLEAN NOT NULL DEFAULT TRUE,
    credentials_non_expired BOOLEAN NOT NULL DEFAULT TRUE,

    failed_login_attempts   SMALLINT NOT NULL DEFAULT 0,
    locked_until            TIMESTAMPTZ,
    last_login_at           TIMESTAMPTZ,
    password_changed_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_auth_user_failed_login_attempts
        CHECK (failed_login_attempts >= 0),
    CONSTRAINT ck_auth_user_email_basic
        CHECK (POSITION('@' IN email) > 1)
);

-- Case-insensitive uniqueness without requiring CITEXT.
CREATE UNIQUE INDEX ux_auth_user_email_ci
    ON auth_user (LOWER(email));

CREATE UNIQUE INDEX ux_auth_user_username_ci
    ON auth_user (LOWER(username));


CREATE TABLE security_role (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,

    CONSTRAINT ck_security_role_code
        CHECK (code ~ '^ROLE_[A-Z0-9_]+$')
);


CREATE TABLE security_permission (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(60) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,

    CONSTRAINT ck_security_permission_code
        CHECK (code ~ '^PERM_[A-Z0-9_]+$')
);


CREATE TABLE security_user_role (
    user_id     BIGINT NOT NULL,
    role_id     SMALLINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_security_user_role_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_security_user_role_role
        FOREIGN KEY (role_id)
        REFERENCES security_role (id)
        ON DELETE RESTRICT
);


CREATE TABLE security_role_permission (
    role_id       SMALLINT NOT NULL,
    permission_id SMALLINT NOT NULL,

    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_security_role_permission_role
        FOREIGN KEY (role_id)
        REFERENCES security_role (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_security_role_permission_permission
        FOREIGN KEY (permission_id)
        REFERENCES security_permission (id)
        ON DELETE CASCADE
);


-- Store only SHA-256 (or equivalent) hashes of refresh tokens, never the raw token.
CREATE TABLE auth_refresh_token (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    token_hash          CHAR(64) NOT NULL UNIQUE,
    device_id           VARCHAR(128),
    ip_address          INET,
    user_agent          VARCHAR(512),

    issued_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at          TIMESTAMPTZ NOT NULL,
    revoked_at          TIMESTAMPTZ,
    last_used_at        TIMESTAMPTZ,

    CONSTRAINT fk_auth_refresh_token_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_auth_refresh_token_expiry
        CHECK (expires_at > issued_at)
);


-- One-time password reset token. Store only the token hash.
CREATE TABLE auth_password_reset_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token_hash  CHAR(64) NOT NULL UNIQUE,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,

    CONSTRAINT fk_auth_password_reset_token_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_auth_password_reset_token_expiry
        CHECK (expires_at > created_at)
);


-- One-time email verification token. Store only the token hash.
CREATE TABLE auth_email_verification_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token_hash  CHAR(64) NOT NULL UNIQUE,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,

    CONSTRAINT fk_auth_email_verification_token_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_auth_email_verification_token_expiry
        CHECK (expires_at > created_at)
);


-- Authentication/security audit trail.
CREATE TABLE auth_audit_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    principal     VARCHAR(320),
    event_type    VARCHAR(60) NOT NULL,
    success       BOOLEAN NOT NULL,
    ip_address    INET,
    user_agent    VARCHAR(512),
    details       JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_auth_audit_event_user
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE SET NULL
);


CREATE INDEX ix_security_user_role_role
    ON security_user_role (role_id, user_id);

CREATE INDEX ix_security_role_permission_permission
    ON security_role_permission (permission_id, role_id);

CREATE INDEX ix_auth_refresh_token_user
    ON auth_refresh_token (user_id);

CREATE INDEX ix_auth_refresh_token_active
    ON auth_refresh_token (user_id, expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX ix_auth_password_reset_token_active
    ON auth_password_reset_token (user_id, expires_at)
    WHERE consumed_at IS NULL;

CREATE INDEX ix_auth_email_verification_token_active
    ON auth_email_verification_token (user_id, expires_at)
    WHERE consumed_at IS NULL;

CREATE INDEX ix_auth_audit_event_user_created
    ON auth_audit_event (user_id, created_at DESC);

CREATE INDEX ix_auth_audit_event_type_created
    ON auth_audit_event (event_type, created_at DESC);


CREATE OR REPLACE FUNCTION set_auth_user_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_auth_user_updated_at
BEFORE UPDATE ON auth_user
FOR EACH ROW
EXECUTE FUNCTION set_auth_user_updated_at();
