-- V4__create_claims.sql
-- Domain schema and permissions for the reclamation administration module.

CREATE TABLE claims (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claimant        VARCHAR(160) NOT NULL,
    provider        VARCHAR(160) NOT NULL,
    invoice_number  VARCHAR(80) NOT NULL,
    amount          NUMERIC(14, 2) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    description     TEXT,
    created_by      BIGINT NOT NULL,
    updated_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_claims_amount_non_negative
        CHECK (amount >= 0),

    CONSTRAINT ck_claims_status
        CHECK (status IN ('DRAFT', 'IN_REVIEW', 'PENDING', 'APPROVED', 'REJECTED')),

    CONSTRAINT fk_claims_created_by
        FOREIGN KEY (created_by)
        REFERENCES auth_user (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_claims_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES auth_user (id)
        ON DELETE SET NULL
);

CREATE INDEX ix_claims_claimant
    ON claims (LOWER(claimant));

CREATE INDEX ix_claims_provider
    ON claims (LOWER(provider));

CREATE INDEX ix_claims_invoice_number
    ON claims (LOWER(invoice_number));

CREATE INDEX ix_claims_status_created
    ON claims (status, created_at DESC);

CREATE INDEX ix_claims_created_at
    ON claims (created_at DESC);

CREATE OR REPLACE FUNCTION set_claims_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_claims_updated_at
BEFORE UPDATE ON claims
FOR EACH ROW
EXECUTE FUNCTION set_claims_updated_at();

INSERT INTO security_permission (code, description)
VALUES
    ('PERM_CLAIM_READ',   'Read claims'),
    ('PERM_CLAIM_CREATE', 'Create claims'),
    ('PERM_CLAIM_UPDATE', 'Update claims'),
    ('PERM_CLAIM_DELETE', 'Delete claims')
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

INSERT INTO security_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM security_role r
JOIN security_permission p
  ON p.code IN ('PERM_CLAIM_READ', 'PERM_CLAIM_CREATE')
WHERE r.code = 'ROLE_USER'
ON CONFLICT DO NOTHING;

INSERT INTO security_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM security_role r
JOIN security_permission p
  ON p.code IN ('PERM_CLAIM_READ', 'PERM_CLAIM_CREATE', 'PERM_CLAIM_UPDATE')
WHERE r.code = 'ROLE_MANAGER'
ON CONFLICT DO NOTHING;

INSERT INTO security_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM security_role r
JOIN security_permission p
  ON p.code IN ('PERM_CLAIM_READ', 'PERM_CLAIM_CREATE', 'PERM_CLAIM_UPDATE', 'PERM_CLAIM_DELETE')
WHERE r.code = 'ROLE_ADMIN'
ON CONFLICT DO NOTHING;
